#!/usr/bin/env bash
# command for installing nginx on a web server

sudo apt-get udate 
sudo apt-get install nginx
sudo ufw "Nginx HTTP"

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx restart
