#!/usr/bin/env bash
# install nginx on web-01

sudo apt-get udate 
sudo apt-get install nginx
sudo ufw allow "Nginx HTTP"

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx start
