#!/usr/bin/env bash
# Configuring web-01 HTTP response header

# updating packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index page
echo "Hello World!" | sudo tee /var/ww/html/index.html
i
# Performing a redirection
new_string=" server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Lawson-JR permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a custom error page

echo "Ceci n'est pas une page" | sudo tee /var/ww/html/404.html

# Custom HTTP response header

sudo sed -i "server_name _:/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test for syntax error 
sudo nginx -t

# Restart nginx 
sudo service nginx restart
