#!/usr/bin/env bash
# Configure an Nginx server to listen to port 80

# remove default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen to port 80 for all active IPVs (IPv4)
ln -m /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
